org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
android.javaCompile.suppressSourceTargetDeprecationWarning=true
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoibW90b3JpbnUiLCJhIjoiY21uNTEzeDlwMDdiaTJwczlxdzM0eXplMSJ9.TCxdZPlDy2MiOutEqrcPQA
