// GENERATED by BIKERGRAM Phase2 Auth Debug HTTP v2
// Standalone debug screen to test api.bikergram.com auth endpoints from Flutter Web.
// Endpoints expected:
//   GET  /health.php
//   POST /register.php   {email,password}
//   POST /login.php      {email,password}
//   GET  /me.php         Authorization: Bearer <accessToken>
//   POST /refresh.php    {refreshToken}  OR Authorization: Bearer <refreshToken>
//   POST /logout.php     {refreshToken}  OR Authorization: Bearer <refreshToken>
//
// Notes:
// - CORS must allow your local origin (e.g. http://127.0.0.1:5174)
// - This file does NOT depend on your existing debug screen implementation.

import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const AuthDebugHttpV2App());
}

class AuthDebugHttpV2App extends StatelessWidget {
  const AuthDebugHttpV2App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bikergram Auth Debug (HTTP v2)',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.blueGrey),
      home: const AuthDebugHttpV2Screen(),
    );
  }
}

class AuthDebugHttpV2Screen extends StatefulWidget {
  const AuthDebugHttpV2Screen({super.key});

  @override
  State<AuthDebugHttpV2Screen> createState() => _AuthDebugHttpV2ScreenState();
}

class _AuthDebugHttpV2ScreenState extends State<AuthDebugHttpV2Screen> {
  final _baseUrlCtrl = TextEditingController(text: 'https://api.bikergram.com');
  final _emailCtrl = TextEditingController(text: 'test@example.com');
  final _passCtrl = TextEditingController(text: 'Test1234!');
  final _logCtrl = TextEditingController();

  String? _accessToken;
  String? _refreshToken;

  void _log(Object msg) {
    final ts = DateTime.now().toIso8601String().replaceFirst('T', ' ').split('.').first;
    _logCtrl.text = '[${ts}] $msg\n${_logCtrl.text}';
  }

  Dio _dio() {
    final baseUrl = _baseUrlCtrl.text.trim().replaceAll(RegExp(r'\/+$'), '');
    return Dio(
      BaseOptions(
        baseUrl: baseUrl,
        connectTimeout: const Duration(seconds: 10),
        receiveTimeout: const Duration(seconds: 15),
        sendTimeout: const Duration(seconds: 15),
        headers: <String, dynamic>{
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        },
        validateStatus: (s) => s != null && s >= 200 && s < 600,
      ),
    );
  }

  Map<String, dynamic> _prettyResponse(Response res) {
    dynamic data = res.data;
    if (data is String) {
      try { data = jsonDecode(data); } catch (_) {}
    }
    return <String, dynamic>{
      if (data is Map || data is List) 'body': data else 'body': data?.toString(),
      '_status': res.statusCode,
      '_headers': {
        'content-type': res.headers.value('content-type'),
      },
    };
  }

  String? _pickToken(dynamic body, List<String> keys) {
    if (body is! Map) return null;
    for (final k in keys) {
      final v = body[k];
      if (v is String && v.isNotEmpty) return v;
    }
    // also check nested {data:{...}}
    final d = body['data'];
    if (d is Map) {
      for (final k in keys) {
        final v = d[k];
        if (v is String && v.isNotEmpty) return v;
      }
    }
    return null;
  }

  Future<void> _health() async {
    _log('--- HEALTH ---');
    try {
      final dio = _dio();
      final res = await dio.get('/health.php');
      _log(const JsonEncoder.withIndent('  ').convert(_prettyResponse(res)));
    } on DioException catch (e) {
      _log('ERROR DioException: ${e.message}');
    } catch (e) {
      _log('ERROR: $e');
    } finally {
      _log('--- HEALTH done ---');
    }
  }

  Future<void> _register() async {
    final email = _emailCtrl.text.trim();
    final password = _passCtrl.text;
    _log('--- REGISTER ---');
    try {
      final dio = _dio();
      final res = await dio.post('/register.php', data: jsonEncode({'email': email, 'password': password}));
      final pretty = _prettyResponse(res);
      _log(const JsonEncoder.withIndent('  ').convert(pretty));

      final body = (res.data is String) ? jsonDecode(res.data) : res.data;
      final access = _pickToken(body, const ['accessToken','access_token','token','jwt']);
      final refresh = _pickToken(body, const ['refreshToken','refresh_token','refresh']);
      if (access != null || refresh != null) {
        setState(() {
          _accessToken = access ?? _accessToken;
          _refreshToken = refresh ?? _refreshToken;
        });
        _log('TokenStore: updated (from REGISTER)');
      }
    } on DioException catch (e) {
      _log('ERROR DioException: ${e.message}');
    } catch (e) {
      _log('ERROR: $e');
    } finally {
      _log('--- REGISTER done ---');
    }
  }

  Future<void> _login() async {
    final email = _emailCtrl.text.trim();
    final password = _passCtrl.text;
    _log('--- LOGIN ---');
    try {
      final dio = _dio();
      final res = await dio.post('/login.php', data: jsonEncode({'email': email, 'password': password}));
      final pretty = _prettyResponse(res);
      _log(const JsonEncoder.withIndent('  ').convert(pretty));

      final body = (res.data is String) ? jsonDecode(res.data) : res.data;
      final access = _pickToken(body, const ['accessToken','access_token','token','jwt']);
      final refresh = _pickToken(body, const ['refreshToken','refresh_token','refresh']);
      if (access != null || refresh != null) {
        setState(() {
          _accessToken = access ?? _accessToken;
          _refreshToken = refresh ?? _refreshToken;
        });
        _log('TokenStore: updated (from LOGIN)');
      }
    } on DioException catch (e) {
      _log('ERROR DioException: ${e.message}');
    } catch (e) {
      _log('ERROR: $e');
    } finally {
      _log('--- LOGIN done ---');
    }
  }

  Future<void> _me() async {
    _log('--- ME ---');
    try {
      final dio = _dio();
      final tok = _accessToken?.trim();
      final opts = Options(headers: tok != null && tok.isNotEmpty ? {'Authorization': 'Bearer $tok'} : null);
      final res = await dio.get('/me.php', options: opts);
      _log(const JsonEncoder.withIndent('  ').convert(_prettyResponse(res)));
    } on DioException catch (e) {
      _log('ERROR DioException: ${e.message}');
    } catch (e) {
      _log('ERROR: $e');
    } finally {
      _log('--- ME done ---');
    }
  }

  Future<void> _refresh() async {
    _log('--- REFRESH ---');
    try {
      final dio = _dio();
      final rt = _refreshToken?.trim();
      final res = await dio.post('/refresh.php', data: jsonEncode({'refreshToken': rt ?? ''}));
      _log(const JsonEncoder.withIndent('  ').convert(_prettyResponse(res)));

      // If refresh returns a new accessToken/refreshToken, update them.
      final body = (res.data is String) ? jsonDecode(res.data) : res.data;
      final access = _pickToken(body, const ['accessToken','access_token','token','jwt']);
      final refresh = _pickToken(body, const ['refreshToken','refresh_token','refresh']);
      if (access != null || refresh != null) {
        setState(() {
          _accessToken = access ?? _accessToken;
          _refreshToken = refresh ?? _refreshToken;
        });
        _log('TokenStore: updated (from REFRESH)');
      }
    } on DioException catch (e) {
      _log('ERROR DioException: ${e.message}');
    } catch (e) {
      _log('ERROR: $e');
    } finally {
      _log('--- REFRESH done ---');
    }
  }

  Future<void> _logout() async {
    _log('--- LOGOUT ---');
    try {
      final dio = _dio();
      final rt = _refreshToken?.trim();
      final res = await dio.post('/logout.php', data: jsonEncode({'refreshToken': rt ?? ''}));
      _log(const JsonEncoder.withIndent('  ').convert(_prettyResponse(res)));
      setState(() {
        _accessToken = null;
        _refreshToken = null;
      });
      _log('TokenStore: cleared (after LOGOUT)');
    } on DioException catch (e) {
      _log('ERROR DioException: ${e.message}');
    } catch (e) {
      _log('ERROR: $e');
    } finally {
      _log('--- LOGOUT done ---');
    }
  }

  void _clearLog() {
    _logCtrl.text = '';
  }

  @override
  void dispose() {
    _baseUrlCtrl.dispose();
    _emailCtrl.dispose();
    _passCtrl.dispose();
    _logCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tokenInfo = 'access: ${_accessToken == null ? '—' : 'set'} | refresh: ${_refreshToken == null ? '—' : 'set'}';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Bikergram Auth Debug (HTTP v2)'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          children: [
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _baseUrlCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Base URL',
                      hintText: 'https://api.bikergram.com',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _emailCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Email',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: TextField(
                    controller: _passCtrl,
                    obscureText: true,
                    decoration: const InputDecoration(
                      labelText: 'Password',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Align(
              alignment: Alignment.centerLeft,
              child: Text(tokenInfo, style: Theme.of(context).textTheme.bodySmall),
            ),
            const SizedBox(height: 10),
            Wrap(
              spacing: 10,
              runSpacing: 10,
              children: [
                ElevatedButton(onPressed: _health, child: const Text('HEALTH')),
                ElevatedButton(onPressed: _register, child: const Text('REGISTER')),
                ElevatedButton(onPressed: _login, child: const Text('LOGIN')),
                ElevatedButton(onPressed: _me, child: const Text('ME')),
                ElevatedButton(onPressed: _refresh, child: const Text('REFRESH')),
                ElevatedButton(onPressed: _logout, child: const Text('LOGOUT')),
                OutlinedButton(onPressed: _clearLog, child: const Text('CLEAR LOG')),
              ],
            ),
            const SizedBox(height: 10),
            Expanded(
              child: TextField(
                controller: _logCtrl,
                maxLines: null,
                expands: true,
                readOnly: true,
                decoration: const InputDecoration(
                  labelText: 'Log',
                  border: OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
